title: Larasati's Portfolio Page
description: > # this means to ignore newlines until "baseurl:"
  Larasati's project portfolio in data visualization, data wrangling, and UI design.
  Tools used are Python, Excel, Tableau, and Github.
  Posts sorted descending (most recent files shown on top).
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Larasati # add your name
author-img: larasati.png # add your photo
about-author: Aspiring data analyst who focuses on data visualization, wrangling, and presenting. I make numbers look pretty. # add description
social-resume:  # add your Resume handle
social-twitter: meng_sanyo # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: git-larasati # add your Github handle
social-linkedin: larasati-prabowo # add your Linkedin handle
social-email: mailbox.larasati@gmail.com # add your Email address

# # Disqus
# discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
